excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cihanblt.github.io
title: my first page
email: cihanblt@gmail.com
author: cihanblt
description: My awesome new site
paginate: 3
google_analytics: 